name: bmi_calculator
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
    
  fluttertoast: ^8.2.2
  google_fonts: ^6.1.0
  line_icons: ^2.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  dio: ^5.3.3
  dio_cache_interceptor: ^3.4.4
  pretty_dio_logger: ^1.3.1
  firebase_messaging: ^14.7.3
  dots_indicator: ^3.0.0
  intl: ^0.18.1
  flutter_rating_bar: ^4.0.1
  syncfusion_flutter_calendar: ^23.1.44
  table_calendar: ^3.0.9
  url_launcher: ^6.2.2
  flutter_animate: ^4.3.0
  carousel_slider: ^4.2.1
  cached_network_image: ^3.3.0
  path_provider: ^2.1.1
  firebase_core: ^2.24.2
  shimmer: ^3.0.0
  flutter_launcher_icons: ^0.11.0
  photo_view: ^0.14.0
  webview_flutter: ^3.0.4
  pull_to_refresh: ^2.0.0
  lottie: ^2.7.0
  image_picker: ^1.0.7
  
dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"

flutter: 
  uses-material-design: true

  assets:
    - assets/images/

