name: bmi_calculator
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  carousel_slider: ^4.2.1
  fluttertoast: ^8.2.2
  google_fonts: ^6.1.0
  line_icons: ^2.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  dio: ^5.3.3
  dio_cache_interceptor: ^3.4.4
  pretty_dio_logger: ^1.3.1
  firebase_messaging: ^14.7.3
  dots_indicator: ^3.0.0
  intl: ^0.18.1
  flutter_rating_bar: ^4.0.1
  syncfusion_flutter_calendar: ^23.1.44
  table_calendar: ^3.0.9
  url_launcher: ^6.2.1
  qr_flutter: ^4.1.0
  flutter_launcher_icons: ^0.11.0
  lottie: ^2.7.0
  font_awesome_flutter: ^10.3.0
  
dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Light.ttf
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Medium.ttf
        - asset: assets/fonts/Quicksand-SemiBold.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf

    - family: Vinila Test
      fonts:
        - asset: assets/fonts/VinilaTest-Light.otf
        - asset: assets/fonts/VinilaTest-Regular.otf
        # - asset: assets/fonts/VinilaTest-Medium.otf
        # - asset: assets/fonts/VinilaTest-SemiBold.otf
        - asset: assets/fonts/VinilaTest-Bold.otf

